// Code generated by "stringer -type CE -linecomment -output string.go"; DO NOT EDIT.

package render

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownError - -1]
	_ = x[DbError-100001]
	_ = x[RedisError-100002]
	_ = x[LostConnectionError-100003]
	_ = x[InvalidParams-101001]
	_ = x[InvalidRequest-101002]
	_ = x[SystemBusy-101003]
	_ = x[DbRecordNotExist-101404]
}

const (
	_CE_name_0 = "未知错误"
	_CE_name_1 = "系统错误系统错误系统错误"
	_CE_name_2 = "请求参数错误请求错误系统繁忙请稍后再试"
	_CE_name_3 = "数据不存在"
)

var (
	_CE_index_1 = [...]uint8{0, 12, 24, 36}
	_CE_index_2 = [...]uint8{0, 18, 30, 57}
)

func (i CE) String() string {
	switch {
	case i == -1:
		return _CE_name_0
	case 100001 <= i && i <= 100003:
		i -= 100001
		return _CE_name_1[_CE_index_1[i]:_CE_index_1[i+1]]
	case 101001 <= i && i <= 101003:
		i -= 101001
		return _CE_name_2[_CE_index_2[i]:_CE_index_2[i+1]]
	case i == 101404:
		return _CE_name_3
	default:
		return "CE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
